// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sausbasomjmrevflfgzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhdXNiYXNvbWptcmV2ZmxmZ3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzI3OTgsImV4cCI6MjA1NzYwODc5OH0.DVbep7zRZx8P8m6CHS2GC_B1fjevJN0o7n1-hYG1ZGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);